apiVersion: apps/v1
kind: Deployment
metadata:
  name: stardew-app
spec:
  selector:
    matchLabels:
      app: stardew-app
  replicas: 2
  template:
    metadata:
      labels:
        app: stardew-app
    spec:
      containers:
        - name: stardew-app
          image: vregistry.azurecr.io/stardew/app:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: redis-password
            - name: DB_HOST
              value: mongodb
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: db-password
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: azure-api-version
            - name: ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: azure-endpoint
            - name: SUBSCRIPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: azure-subscription-key
            - name: DEPLOYMENT
              valueFrom:
                secretKeyRef:
                  name: stardew-secrets
                  key: azure-deployment
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keyvault-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: stardew-app
spec:
  selector:
    app: stardew-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
