apiVersion: apps/v1
kind: Deployment
metadata:
  name: stardew-web
spec:
  selector:
    matchLabels:
      app: stardew-web
  replicas: 1
  template:
    metadata:
      labels:
        app: stardew-web
    spec:
      containers:
        - name: stardew-web
          image: vregistry.azurecr.io/stardew/web:latest
          ports:
            - containerPort: 80
          env:
            - name: SERVER_NAME
              value: stardew-web
            - name: API_HOST
              value: stardew-app
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: stardew-web
spec:
  type: LoadBalancer
  selector:
    app: stardew-web
  ports:
    - port: 80
      targetPort: 80
